import { Product } from "@/types/product";

const Products: Product[] = [
  {
    id: "1",
    slug: "classic-crewneck-t-shirt",
    name: "Classic Crewneck T-Shirt",
    category: "T-Shirts",
    catalog: "Best Seller",
    price: 100,
    originalPrice: 150,
    discount: 30,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "2",
    slug: "premium-oxford-shirt",
    name: "Premium Oxford Shirt",
    category: "Shirts",
    catalog: "Best Seller",
    price: 120,
    originalPrice: 180,
    discount: 33,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "3",
    slug: "slim-fit-polo-shirt",
    name: "Slim Fit Polo Shirt",
    category: "T-Shirts",
    catalog: "Best Seller",
    price: 90,
    originalPrice: 130,
    discount: 31,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "4",
    slug: "casual-linen-shirt",
    name: "Casual Linen Shirt",
    category: "Shirts",
    catalog: "Best Seller",
    price: 110,
    originalPrice: 160,
    discount: 31,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "5",
    slug: "graphic-print-tee",
    name: "Graphic Print Tee",
    category: "T-Shirts",
    catalog: "Best Seller",
    price: 85,
    originalPrice: 120,
    discount: 29,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "6",
    slug: "formal-dress-shirt",
    name: "Formal Dress Shirt",
    category: "Shirts",
    catalog: "Best Seller",
    price: 130,
    originalPrice: 190,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "7",
    slug: "striped-henley-tee",
    name: "Striped Henley Tee",
    category: "T-Shirts",
    catalog: "New Arrival",
    price: 95,
    originalPrice: 140,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "8",
    slug: "checkered-flannel-shirt",
    name: "Checkered Flannel Shirt",
    category: "Shirts",
    catalog: "New Arrival",
    price: 115,
    originalPrice: 170,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "9",
    slug: "v-neck-basic-tee",
    name: "V-Neck Basic Tee",
    category: "T-Shirts",
    catalog: "New Arrival",
    price: 80,
    originalPrice: 120,
    discount: 33,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "10",
    slug: "denim-button-up-shirt",
    name: "Denim Button-Up Shirt",
    category: "Shirts",
    catalog: "New Arrival",
    price: 125,
    originalPrice: 180,
    discount: 31,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "11",
    slug: "long-sleeve-tee",
    name: "Long Sleeve Tee",
    category: "T-Shirts",
    catalog: "New Arrival",
    price: 90,
    originalPrice: 135,
    discount: 33,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "12",
    slug: "printed-hawaiian-shirt",
    name: "Printed Hawaiian Shirt",
    category: "Shirts",
    catalog: "New Arrival",
    price: 105,
    originalPrice: 155,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "13",
    slug: "vintage-wash-tee",
    name: "Vintage Wash Tee",
    category: "T-Shirts",
    catalog: "Trending",
    price: 95,
    originalPrice: 140,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "14",
    slug: "slim-fit-dress-shirt",
    name: "Slim Fit Dress Shirt",
    category: "Shirts",
    catalog: "Trending",
    price: 120,
    originalPrice: 175,
    discount: 31,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "15",
    slug: "pocket-detail-tee",
    name: "Pocket Detail Tee",
    category: "T-Shirts",
    catalog: "Trending",
    price: 85,
    originalPrice: 125,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "16",
    slug: "chambray-work-shirt",
    name: "Chambray Work Shirt",
    category: "Shirts",
    catalog: "Trending",
    price: 110,
    originalPrice: 165,
    discount: 33,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "17",
    slug: "raglan-sleeve-tee",
    name: "Raglan Sleeve Tee",
    category: "T-Shirts",
    catalog: "Trending",
    price: 90,
    originalPrice: 130,
    discount: 31,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "18",
    slug: "mandarin-collar-shirt",
    name: "Mandarin Collar Shirt",
    category: "Shirts",
    catalog: "Trending",
    price: 115,
    originalPrice: 170,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "19",
    slug: "embroidered-logo-tee",
    name: "Embroidered Logo Tee",
    category: "T-Shirts",
    catalog: "Featured",
    price: 100,
    originalPrice: 145,
    discount: 31,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "20",
    slug: "pinstripe-formal-shirt",
    name: "Pinstripe Formal Shirt",
    category: "Shirts",
    catalog: "Featured",
    price: 130,
    originalPrice: 190,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "21",
    slug: "athletic-fit-tee",
    name: "Athletic Fit Tee",
    category: "T-Shirts",
    catalog: "Featured",
    price: 95,
    originalPrice: 140,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "22",
    slug: "corduroy-button-down",
    name: "Corduroy Button Down",
    category: "Shirts",
    catalog: "Featured",
    price: 120,
    originalPrice: 175,
    discount: 31,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "23",
    slug: "color-block-tee",
    name: "Color Block Tee",
    category: "T-Shirts",
    catalog: "Featured",
    price: 90,
    originalPrice: 135,
    discount: 33,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "24",
    slug: "short-sleeve-shirt",
    name: "Short Sleeve Shirt",
    category: "Shirts",
    catalog: "Featured",
    price: 105,
    originalPrice: 155,
    discount: 32,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "25",
    slug: "oversized-tee",
    name: "Oversized Tee",
    category: "T-Shirts",
    catalog: "Sale",
    price: 75,
    originalPrice: 120,
    discount: 38,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "26",
    slug: "plaid-flannel-shirt",
    name: "Plaid Flannel Shirt",
    category: "Shirts",
    catalog: "Sale",
    price: 95,
    originalPrice: 160,
    discount: 41,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "27",
    slug: "distressed-vintage-tee",
    name: "Distressed Vintage Tee",
    category: "T-Shirts",
    catalog: "Sale",
    price: 70,
    originalPrice: 115,
    discount: 39,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "28",
    slug: "western-style-shirt",
    name: "Western Style Shirt",
    category: "Shirts",
    catalog: "Sale",
    price: 90,
    originalPrice: 150,
    discount: 40,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "29",
    slug: "tie-dye-tee",
    name: "Tie Dye Tee",
    category: "T-Shirts",
    catalog: "Sale",
    price: 65,
    originalPrice: 110,
    discount: 41,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
  {
    id: "30",
    slug: "military-inspired-shirt",
    name: "Military Inspired Shirt",
    category: "Shirts",
    catalog: "Sale",
    price: 85,
    originalPrice: 140,
    discount: 39,
    size: ["42", "40", "38", "36"],
    thumbnail: "/dummy.jpg",
  },
];

export const getProducts = (
  catalog: "Best Seller" | "New Arrival" | "Trending" | "Featured" | "Sale",
  limit: number = 5
): Product[] => {
  return Products.filter((product) => product.catalog === catalog).slice(
    0,
    limit
  );
};
